### ISSUE TITLE
Create database schema

### ISSUE THREAD

**Issue by bopke** [Re-Host-pl/rh-dns#1]

**Comment by Graleszczur** [comment]
Preferably use DB Designer as a tool.

**Comment by Graleszczur** [comment]
Just a simple table with entry details like domain and subdomain.

**Comment by Rahano** [comment]
![p2](https://user-images.githubusercontent.com/56368819/66861788-f3228b80-ef8f-11e9-9434-0ad0c32fdc51.png)

**Comment by Graleszczur** [comment]
Looks good to me.
